FROM registry.es.datio/dockerbaseimages/jessie_slim_java-8u121:latest

COPY akka-heimdallr-1.0-SNAPSHOT-with-dependencies.jar /akka-heimdallr-1.0-SNAPSHOT-with-dependencies.jar

CMD ["java","-jar","/akka-heimdallr-1.0-SNAPSHOT-with-dependencies.jar"]